# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first terms will be:

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# naive solution first 
fib = [0,1]
i, f = 2, 0
f_max = 4*10**6
f_sum = 0
while f < f_max:
    f = fib[i-1] + fib[i-2]
    fib.append(f)
    i += 1
    if f % 2 == 0:
        f_sum += f
print(f_sum)
